SELECT = ['SELECT', 'SELECIONE']
UPDATE = ['UPDATE', 'ATUALIZE']
DELETE = ['DELETE', 'DELETE']
INSERT = ['INSERT', 'INSIRA']
FROM = ['FROM', 'DE']
WHERE = ['WHERE', 'ONDE']
NULL = ['NULL', 'NULO']
IS = ['IS', 'É']
NOT = ['NOT', 'NÃO']
DISTINCT = ['DISTINCT', 'DISTINTOS']
VALUES = ['VALUES', 'VALORES']
INTO = ['INTO', 'EM']
SET = ['SET', 'DEFINA']
AND = ['AND', 'E']
OR = ['OR', 'OU']

# DDL KEYWORDS
CREATE = "CREATE"
ALTER = "ALTER"
DROP = "DROP"
TABLE = "TABLE"
ADD = "ADD"
PRIMARY = "PRIMARY"
KEY = "KEY"
RENAME = "RENAME"
TO = "TO"

SQLDDL = [CREATE, ALTER, DROP, TABLE, ADD, PRIMARY, KEY, RENAME, TO]

CRIE = "CRIE"
ALTERE = "ALTERE"
EXCLUA = "EXCLUA"
TABELA = "TABELA"
ADICIONE = "ADICIONE"
IDENTIFICADOR = "IDENTIFICADOR"
CHAVE = "CHAVE"
RENOMEIE = "RENOMEIE"
PARA = "PARA"

PSQLDDL = [CRIE, ALTERE, EXCLUA, TABELA, ADICIONE, IDENTIFICADOR, CHAVE, RENOMEIE, PARA]

DDL = SQLDDL + PSQLDDL

# END DDL

# DATA TYPES

INT = "INT"
TEXT = "TEXT"
REAL = "REAL"

INTEIRO = "INTEIRO"
TEXTO = "TEXTO"

ALLDATATYPES = [TEXT, INT, REAL, INTEIRO, TEXTO]

# END DATA TYPES

LOGICAL_OPERATIONS = AND + OR + NOT + IS

ALL = SELECT + UPDATE + DELETE + INSERT + FROM + WHERE + NULL + IS + NOT + DISTINCT + VALUES + INTO + SET + AND + OR + ['*', 'TUDO'] + DDL + ALLDATATYPES


KEYWORDS = {
	'SELECIONE' : 'SELECT',
	'ATUALIZE' : 'UPDATE',
	'DELETE' : 'DELETE',
	'INSIRA' : 'INSERT',
	'DE' : 'FROM',
	'ONDE' : 'WHERE',
	'NULO' : 'NULL',
	'É' : 'IS',
	'NÃO' : 'NOT',
	'DISTINTOS' : 'DISTINCT',
	'VALORES' : 'VALUES',
	'EM' : 'INTO',
	'DEFINA' : 'SET',
	'TUDO' : '*',
	'E' : 'AND',
	'OU' : 'OR',
	CRIE : CREATE,
	ALTERE : ALTER,
	EXCLUA : DROP,
	ADICIONE : ADD,
	TABELA : TABLE,
	IDENTIFICADOR : PRIMARY,
	CHAVE : KEY,
	INTEIRO : INT,
	TEXTO : TEXT,
	REAL : REAL,
	RENOMEIE : RENAME,
	PARA : TO
}

PSQL = {
	'SELECT' : 'SELECIONA',
	'UPDATE' : 'ATUALIZE',
	'DELETE' : 'DELETE',
	'INSERT' : 'INSIRA',
	'FROM' : 'DE',
	'WHERE' : 'ONDE',
	'NULL' : 'NULO',
	'IS' : 'É',
	'NOT' : 'NÃO',
	'DISTINCT' : 'DISTINTOS',
	'VALUES' : 'VALORES',
	'INTO' : 'EM',
	'SET' : 'DEFINA',
	'*' : 'TUDO',
	'OR' : 'OU',
	'AND' : 'E',
	CREATE : CRIE,
	ALTER : ALTERE,
	DROP : EXCLUA,
	ADD : ADICIONE,
	TABLE : TABELA,
	PRIMARY : IDENTIFICADOR,
	KEY : CHAVE,
	TEXT : TEXTO,
	INT : INTEIRO,
	REAL : REAL,
	RENAME : RENOMEIE,
	TO : PARA
}

def GetKeyword(value):
	return KEYWORDS[value]
	#return ALL[ALL.index(value)]

def GetPSQL(value):
	try:
		return PSQL[value]
	except:
		return value