SELECT = 'SELECT'
ALLCOLUMNS = '*'
UPDATE = 'UPDATE'
DELETE = 'DELETE'
INSERT = 'INSERT'
FROM = 'FROM'
WHERE = 'WHERE'
NULL = 'NULL'
IS = 'IS'
NOT = 'NOT'
DISTINCT = 'DISTINCT'
VALUES = 'VALUES'
INTO = 'INTO'
SET = 'SET'
AND = 'AND'
OR = 'OR'

SQLDQL = [SELECT, ALLCOLUMNS]
SQLDML = [UPDATE, INSERT, DELETE, FROM, WHERE, NULL, IS, NOT, DISTINCT, VALUES, INTO, SET, AND, OR]

SELECIONE = 'SELECIONE'
ATUALIZE = 'ATUALIZE'
TUDO = 'TUDO'
INSIRA = 'INSIRA'
DE = 'DE'
ONDE = 'ONDE'
NULO = 'NULO'
É = 'É'
NAO = 'NÃO'
DISTINTOS = 'DISTINTOS'
VALORES = 'VALORES'
EM = 'EM'
DEFINA = 'DEFINA'
E = 'E'
OU = 'OU'

PSQLDQL = [SELECIONE, TUDO]
PSQLDML = [ATUALIZE, INSIRA, DE, ONDE, NULO, É, NAO, DISTINTOS, VALORES, EM, DEFINA, E, OU]

ALLSQLPLUSDML = SQLDML + SQLDQL + PSQLDQL + PSQLDML

# DDL KEYWORDS
CREATE = "CREATE"
ALTER = "ALTER"
DROP = "DROP"
TABLE = "TABLE"
ADD = "ADD"
PRIMARY = "PRIMARY"
KEY = "KEY"
RENAME = "RENAME"
TO = "TO"

SQLDDL = [CREATE, ALTER, DROP, TABLE, ADD, PRIMARY, KEY, RENAME, TO]

CRIE = "CRIE"
ALTERE = "ALTERE"
EXCLUA = "EXCLUA"
TABELA = "TABELA"
ADICIONE = "ADICIONE"
IDENTIFICADOR = "IDENTIFICADOR"
CHAVE = "CHAVE"
RENOMEIE = "RENOMEIE"
PARA = "PARA"

PSQLDDL = [CRIE, ALTERE, EXCLUA, TABELA, ADICIONE, IDENTIFICADOR, CHAVE, RENOMEIE, PARA]

DDL = SQLDDL + PSQLDDL

# END DDL

# DATA TYPES

INT = "INT"
TEXT = "TEXT"
REAL = "REAL"

INTEIRO = "INTEIRO"
TEXTO = "TEXTO"

PSQLDATATYPES = [REAL, INTEIRO, TEXTO]
ALLDATATYPES = [TEXT, INT, REAL, INTEIRO, TEXTO]

# END DATA TYPES
PSQL_LOGICAL_OPERATIONS = E + OU + NOT + É
LOGICAL_OPERATIONS = AND + OR + NOT + IS

ALL = ALLSQLPLUSDML + ['*', 'TUDO'] + DDL + ALLDATATYPES


KEYWORDS = {
	SELECIONE : SELECT,
	ATUALIZE : UPDATE,
	DELETE : DELETE,
	INSIRA : INSERT,
	DE : FROM,
	ONDE : WHERE,
	NULO : NULL,
	É : IS,
	NAO : NOT,
	DISTINTOS : DISTINCT,
	VALORES : VALUES,
	EM : INTO,
	DEFINA : SET,
	TUDO : ALLCOLUMNS,
	E : AND,
	OU : OR,
	CRIE : CREATE,
	ALTERE : ALTER,
	EXCLUA : DROP,
	ADICIONE : ADD,
	TABELA : TABLE,
	IDENTIFICADOR : PRIMARY,
	CHAVE : KEY,
	INTEIRO : INT,
	TEXTO : TEXT,
	REAL : REAL,
	RENOMEIE : RENAME,
	PARA : TO
}

PSQL = {
	SELECT : SELECIONE,
	UPDATE : ATUALIZE,
	DELETE : DELETE,
	INSERT : INSIRA,
	FROM : DE,
	WHERE : ONDE,
	NULL : NULO,
	IS : É,
	NOT : NAO,
	DISTINCT : DISTINTOS,
	VALUES : VALORES,
	INTO : EM,
	SET : DEFINA,
	ALLCOLUMNS : TUDO,
	OR : OU,
	AND : E,
	CREATE : CRIE,
	ALTER : ALTERE,
	DROP : EXCLUA,
	ADD : ADICIONE,
	TABLE : TABELA,
	PRIMARY : IDENTIFICADOR,
	KEY : CHAVE,
	TEXT : TEXTO,
	INT : INTEIRO,
	REAL : REAL,
	RENAME : RENOMEIE,
	TO : PARA
}

def GetKeyword(value):
	#return KEYWORDS[value]
	return ALL[ALL.index(value)]

def GetPSQL(value):
	try:
		return PSQL[value]
	except:
		return value

def GetSQLKeyword(value):
	try:
		return KEYWORDS[value]
	except:
		return value